name: pbma
description: 'This app provides a comprehensive solution for managing tasks efficiently.'
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  intl: ^0.20.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  fluttertoast: ^8.2.12
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  material_symbols_icons: ^4.2815.0
  flutter_sticky_header: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
