name: pbma
description: "This app provides a comprehensive solution for managing tasks efficiently."
publish_to: "none"
version: 1.0.0+5

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  intl: ^0.20.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  fluttertoast: ^8.2.12
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  material_symbols_icons: ^4.2815.0
  flutter_sticky_header: ^0.8.0
  uuid: ^4.5.1
  google_maps: ^8.1.1
  google_maps_flutter: ^2.12.2
  geolocator: ^14.0.0
  geocoding: ^4.0.0
  collection: ^1.19.1
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  crypto: ^3.0.6
  cached_network_image: ^3.4.1
  firebase_core: ^3.13.1
  firebase_database: ^11.3.7
  firebase_storage: ^12.4.7
  flutter_svg: ^2.1.0
  local_auth: ^2.3.0
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.5.0
  package_info_plus: ^8.0.2
  bcrypt: ^1.1.3
  openpgp: ^3.10.5
  shimmer: ^3.0.0
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/jsons/
