name: pbma
description: ""
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  intl: ^0.20.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
