// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUky2ZxCiHcc2PNwXIK544HPX2lWUga00',
    appId: '1:269030192115:android:6be0c02e4cf5bd193a9886',
    messagingSenderId: '269030192115',
    projectId: 'pbma-460316',
    databaseURL: 'https://pbma-460316-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pbma-460316.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu0_pOKs5UlxncthOaGPCcvDQ6aENkzFs',
    appId: '1:269030192115:ios:2f3c0c356a5f5d4f3a9886',
    messagingSenderId: '269030192115',
    projectId: 'pbma-460316',
    databaseURL: 'https://pbma-460316-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pbma-460316.firebasestorage.app',
    iosBundleId: 'com.sophanit.pbma.ios',
  );
}
